resilience4j:
  ratelimiter:
    instances:
      rateController:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 100ms
  circuitbreaker:
    instances:
      circuitController:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count_based
        sliding-window-size: 10
spring:
  application:
    name: spring-synchronous-interaction
  datasource:
    url: jdbc:postgresql://localhost:5432/mts_homework
    username: postgres
    password: whatever
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  security:
    user:
      name: admin
      password: secret
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator
  prometheus:
    metrics:
      export:
        enabled: true